POST https://moviender-backend-production.up.railway.app/api/users  HTTP/1.1
content-type: application/json

{
    "userName": "probe this",
    "myMovies": "[45654, 200, 654, 2154]"
}

###
POST https://moviender-backend-production.up.railway.app/api/users  HTTP/1.1
content-type: application/json

{
}
